
var buttonColours = ["red","blue","green","yellow"]; //array for colours.

var gamePattern = []; //this array will save the game pattern which is generated by Math.random.
var userClickedPattern = []; //this array will save the pattern where user clicks the button like ['green','blue','red','blue'].

var started = false; 
var level = 0; //this will intitalize the game level to 0.

//this function calling the nextsequence() on keypress and making started = true.
$(document).keypress(function(){
    if(!started){
        $("#level-title").text("level "+ level);
        nextSequence();
        started = true;
    }
});

//this function is storing Id's of buttons which user chooses.
$(".btn").click(function(){
    var userChosenColour = $(this).attr("id");
    userClickedPattern.push(userChosenColour);

    playSound(userChosenColour);
    animatePress(userChosenColour);

    checkAnswer(userChosenColour.length - 1);
});

//this function checks the userPattern and gamePattern with each other if the userPattern will not match gamePattern the game will get over and restarts.
function checkAnswer(currentLevel){
    if (gamePattern[currentLevel] === userClickedPattern[currentLevel]) {
        if (userClickedPattern.length === gamePattern.length) {
            setTimeout(() => {
                nextSequence();
            }, 1000);
        }
    } else{
        playSound("wrong");
        $("body").addClass("game-over");
        $("#level-title").text("Game Over, Press Any Key to Restart");

        setTimeout(() => {
            $("body").removeClass("game-over");
        }, 200);

        startOver();
    }
}

//this function is making sequence for gamePattern and storing it in gamePattern[].
function nextSequence(){
    userClickedPattern = [];
    level++;
    $("#level-title").text("level "+ level);
    
    var randomNumber = Math.floor(Math.random()*4);
    var randomChosenColour = buttonColours[randomNumber];
    gamePattern.push(randomChosenColour);
    
    $("#" + randomChosenColour).fadeIn(100).fadeOut(100).fadeIn(100);
    playSound(randomChosenColour);
}

//this function is making animation when user presses the button.
function animatePress(currentColour){
    $("#" + currentColour).addClass("pressed");
    setTimeout(() => {
        $("#" + currentColour).removeClass("pressed");
    }, 100);
}

//this function is playing sounds for the game.
function playSound(name){
    var audio = new Audio("sounds/"+ name + ".mp3");
    audio.play();
}

//this function will help in reseting the game.
function startOver(){
    level = 0;
    started = false;
    gamePattern = [];
}